package:
  name: omni_custom_gym
  version: 0.0.1

source:
  path: .

requirements:
  build:
    - python 3.7
    - setuptools

build:
  script:
    - python3 -m pip install -v .

about:
  home: https://github.com/AndPatr/ControlClusterUtils
  license: MIT
  summary: Some custom implementations of Tasks and Gyms for for Omniverse Isaac Sim based on Gymnasium. Easy URDF and SRDF import/cloning and simulation configuration exploiting Omniverse API 
