package:
  name: omni_custom_gym
  version: '1.0.0_py{{ py }}'
  
source:
  path: .

requirements:
  build:
    - python 3.7
    - setuptools

about:
  home: https://github.com/AndrePatri/OmniCustomGym
  license: MIT
  summary: Some custom implementations of Tasks and Gyms for Omniverse Isaac Sim based on Gymnasium. Easy URDF and SRDF import/cloning and simulation configuration exploiting Omniverse API 
